language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

install:
  - composer install

script:
    - phpunit --coverage-clover clover-coverage.xml

after_success:
  - composer require satooshi/php-coveralls '^1.0'
  - travis_retry php vendor/bin/coveralls -v