language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

install:
  - composer --no-interaction remove --dev friendsofphp/php-cs-fixer # this fails on hhvm, and we don't need it in Travis
  - composer install

before_script:
  - mkdir coveralls-data

script:
    - vendor/bin/phpunit --coverage-clover coveralls-data/clover-coverage.xml

after_success:
  - composer require satooshi/php-coveralls '^1.0'
  - travis_retry php vendor/bin/coveralls -v